spring.application.name=rodai

# Conexão com o banco PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/acidentes
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log das queries SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger (Documentação da API)
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.packages-to-scan=br.edu.ufcg.rodai.controller
