spring.application.name=rodai

# Conexão com o banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/acidentes
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log das queries SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
